### ISSUE TITLE
Wrong SD pins for 4MB model

### ISSUE THREAD

**Issue by Levak** [tiredboffin/sdwifi#1]
Hi there,

I have found your project thanks to the link you gave in the official firmware, SdWifiBrowser, and after managing to make it work, I can't thank you enough for the work you've done. It really is day and night with all the major problems I encountered with the official one, but solved with yours. 

That being said, I did need to tweak your project to make it work on my model (No clue how to differentiate them btw) that has a 4MB internal Flash. I added this file `pins_arduino.h`:

```c
#ifndef Pins_Arduino_h
#define Pins_Arduino_h

#include <stdint.h>

static const uint8_t TX = 1;
static const uint8_t RX = 3;

static const uint8_t SDA = 21;
static const uint8_t SCL = 22;

static const uint8_t SS = 5;
static const uint8_t MOSI = 23;
static const uint8_t MISO = 19;
static const uint8_t SCK = 18;

static const uint8_t A0 = 36;
static const uint8_t A3 = 39;
static const uint8_t A4 = 32;
static const uint8_t A5 = 33;
static const uint8_t A6 = 34;
static const uint8_t A7 = 35;
static const uint8_t A10 = 4;
static const uint8_t A11 = 0;
static const uint8_t A12 = 2;
static const uint8_t A13 = 15;
static const uint8_t A14 = 13;
static const uint8_t A15 = 12;
static const uint8_t A16 = 14;
static const uint8_t A17 = 27;
static const uint8_t A18 = 25;
static const uint8_t A19 = 26;

static const uint8_t T0 = 4;
static const uint8_t T1 = 0;
static const uint8_t T2 = 2;
static const uint8_t T3 = 15;
static const uint8_t T4 = 13;
static const uint8_t T5 = 12;
static const uint8_t T6 = 14;
static const uint8_t T7 = 27;
static const uint8_t T8 = 33;
static const uint8_t T9 = 32;

static const uint8_t DAC1 = 25;
static const uint8_t DAC2 = 26;

// SDCARD Slot
#define BOARD_HAS_SDMMC
#define SDMMC_D2             12  // SDMMC Data2
#define SDMMC_D3             13  // SDMMC Data3 / SPI CS
#define SDMMC_CMD            15  // SDMMC CMD   / SPI MOSI
#define SDMMC_CLK            14  // SDMMC CLK   / SPI SCK
#define SDMMC_D0              2  // SDMMC Data0 / SPI MISO
#define SDMMC_D1              4  // SDMMC Data1
#define BOARD_MAX_SDMMC_FREQ SDMMC_FREQ_DEFAULT

#endif /* Pins_Arduino_h */
```

I took the SDMMC pin definition from the [official project](https://github.com/tiredboffin/SdWiFiBrowser/blob/main/pins.h#L22-L32).
What's surprising is that I did not have to change the `CS_SENSE_PIN` that you define to `33` but is defined to `32` in theirs. I have no way to verify what is correct because `33` (yours) just works.

I did not make this a PR because I don't know if you somehow have a different model than mine.

Best regards,

**Comment by Levak** [comment]
In the end, I decided to create a PR: https://github.com/tiredboffin/sdwifi/pull/2

**Comment by tiredboffin** [comment]
Thank you for the PR! The code builds and seems to work fine on my SD Wifi Pro card so I guess the cards are identical.

I think the difference comes down to how the host (for e.g. printer) negotiates the SD mode. Based on the SD WiFi Pro schematic, PIN 33 is tied to the DAT3 SD pin. In SPI mode, it acts as a chip select (CS) signal, but in SD 4-bit mode, it’s used for data transfer instead.

This means PIN 33 can reliably indicate if the card is "busy" (e.g., mounted) only when the host is using SPI mode. In 4-bit mode, the pin stays inactive even if the card is mounted but the host is idle. This can make concurrent use of the card tricky, as it raises the risk of file system corruption or "card not available" errors—though, depending on the host’s specific logic, it might still be possible.
